# Generated by Django 4.2.5 on 2024-04-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.CharField(choices=[('health', 'Health'), ('business', 'Business'), ('sports', 'Sports')], default='health', max_length=20),
        ),
    ]
