# Generated by Django 4.2.5 on 2024-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.TextField(),
        ),
    ]
