# Generated by Django 4.2.5 on 2024-04-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Image',
            field=models.URLField(),
        ),
    ]
