# Generated by Django 4.2.5 on 2024-04-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
